Get http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/60160cd37abb5c0d28758da8

###

Post http://localhost:3000/subscribers
Content-Type: application/json



{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###
DELETE http://localhost:3000/subscribers/60160cd37abb5c0d28758da8


###

PATCH  http://localhost:3000/subscribers/6016146d4b3e2d352864ba2b",
Content-Type: application/json

{
    "name": "New Name"
}

# patch request doesnt work with rest client
#but it works in postman!